### ISSUE TITLE
MLVU evaluation error

### ISSUE THREAD

**Issue by arsoyul** [xiaomi-research/q-frame#4]
Thank you for sharing great work. I am currently reproducing your experiments by following your instructions.
But evaluating MLVU on q-frame qwen2vl made the following obstacles.
 
1. Memory issue
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 150.26 GiB. GPU 0 has a total capacity of 79.10 GiB of which 52.58 GiB is free. Including non-PyTorch memory, this process has 26.57 GiB memory in use. Of the allocated memory 25.85 GiB is allocated by PyTorch, and 60.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

 I use 1 H100 for evaluation. Does this Q-frame framework originally require a large memory allocation of around 150GB, or is the shared GitHub code wrong? A large memory allocation has been made only in the MLVU dataset that goes beyond my GPU memory limits.

2. LMMs-Eval framework error
I found that the metric calculation on MLVU made an error: KeyError: 'needle'
Do you know how I can handle this?

**Comment by zhshj0110** [comment]
Thank you for your interest in our work.
Could you share the version information of lmms-eval you are using?

**Comment by arsoyul** [comment]
My llms-eval version is 0.3.0.
The MLVU 'needle' error is solved by replacing the task yaml and utils of the latest lmms-eval. So I am using MLVU_dev for evaluation. 

Your code extract query in the mlvu.
question = text.split("\n")[1][10:]

I checked the real text as follows
2026-01-19 17:37:44.234 | INFO     | lmms_eval.models.query_check:TextImageMatching:41 - mlvu_dev
2026-01-19 17:37:44.234 | INFO     | lmms_eval.models.query_check:TextImageMatching:61 -   Line 0: 'What is a popular activity on the beach during the monsoon season?'
2026-01-19 17:37:44.234 | INFO     | lmms_eval.models.query_check:TextImageMatching:61 -   Line 1: '(A) Picnicking'
2026-01-19 17:37:44.234 | INFO     | lmms_eval.models.query_check:TextImageMatching:61 -   Line 2: '(B) Surfing'
2026-01-19 17:37:44.234 | INFO     | lmms_eval.models.query_check:TextImageMatching:61 -   Line 3: '(C) Playing volleyball'
2026-01-19 17:37:44.234 | INFO     | lmms_eval.models.query_check:TextImageMatching:61 -   Line 4: '(D) Fishing'
2026-01-19 17:37:44.234 | INFO     | lmms_eval.models.query_check:TextImageMatching:61 -   Line 5: ''
2026-01-19 17:37:44.234 | INFO     | lmms_eval.models.query_check:TextImageMatching:61 -   Line 6: 'Only give the best option.'
2026-01-19 17:37:44.234 | INFO     | lmms_eval.models.query_check:TextImageMatching:61 -   Line 7: 'Best option: ('

I think the extraction code should be "question = text.split("\n")[0]". The original version yields about 58%, while revised one yield 64% for mlvu_dev.  How do you think?
